export function queryDom() {
  return {
    loginCard: document.getElementById("event-hub-login-card"),
    loginButton: document.getElementById("event-hub-login-button"),
    loginError: document.getElementById("event-hub-login-error"),
    main: document.getElementById("event-hub-main"),
    loading: document.getElementById("event-hub-loading"),
    loadingText: document.getElementById("event-hub-loading-text"),
    alert: document.getElementById("event-hub-alert"),
    summary: document.getElementById("event-hub-summary"),
    eventName: document.getElementById("event-hub-event-name"),
    scheduleCount: document.getElementById("event-hub-schedule-count"),
    totalParticipants: document.getElementById("event-hub-total-participants"),
    scheduleCards: document.getElementById("event-hub-schedule-list"),
    cardsEmpty: document.getElementById("event-hub-empty"),
    backLink: document.getElementById("event-hub-back-link"),
    manageLink: document.getElementById("event-hub-manage-link"),
    metaNote: document.getElementById("event-hub-meta"),
    scheduleAdminList: document.getElementById("schedule-list"),
    scheduleAdminEmpty: document.getElementById("schedule-empty"),
    scheduleContext: document.getElementById("schedule-context"),
    addScheduleButton: document.getElementById("add-schedule-button"),
    scheduleRefreshButton: document.getElementById("schedule-refresh-button"),
    scheduleDialog: document.getElementById("schedule-dialog"),
    scheduleForm: document.getElementById("schedule-form"),
    scheduleDialogTitle: document.getElementById("schedule-dialog-title"),
    scheduleLabelInput: document.getElementById("schedule-label-input"),
    scheduleDateInput: document.getElementById("schedule-date-input"),
    scheduleStartInput: document.getElementById("schedule-start-input"),
    scheduleEndInput: document.getElementById("schedule-end-input"),
    scheduleError: document.getElementById("schedule-error"),
    confirmDialog: document.getElementById("confirm-dialog"),
    confirmDialogTitle: document.getElementById("confirm-dialog-title"),
    confirmDialogMessage: document.getElementById("confirm-dialog-message"),
    confirmAcceptButton: document.getElementById("confirm-accept-button"),
    confirmCancelButton: document.getElementById("confirm-cancel-button")
  };
}
