export function queryDom() {
  return {
    loginButton: document.getElementById("login-button"),
    loginContainer: document.getElementById("login-container"),
    mainContainer: document.getElementById("main-container"),
    actionPanel: document.getElementById("action-panel"),
    userInfo: document.getElementById("user-info"),
    dictionaryToggle: document.getElementById("dictionary-toggle"),
    dictionaryPanel: document.getElementById("dictionary-panel"),
    logsToggle: document.getElementById("logs-toggle"),
    logsPanel: document.getElementById("logs-panel"),
    cardsContainer: document.getElementById("questions-cards"),
    genreTabContainer: document.getElementById("genre-tab-buttons"),
    scheduleFilter: document.getElementById("schedule-filter"),
    dictionaryTableBody: document.querySelector("#dictionary-table tbody"),
    addTermForm: document.getElementById("add-term-form"),
    newTermInput: document.getElementById("new-term"),
    newRubyInput: document.getElementById("new-ruby"),
    editDialog: document.getElementById("edit-dialog"),
    editTextarea: document.getElementById("edit-textarea"),
    editSaveButton: document.getElementById("edit-save-button"),
    editCancelButton: document.getElementById("edit-cancel-button"),
    actionButtons: ["btn-display", "btn-unanswer", "btn-edit"].map((id) => document.getElementById(id)),
    selectedInfo: document.getElementById("selected-info"),
    selectAllCheckbox: document.getElementById("select-all-checkbox"),
    batchUnanswerBtn: document.getElementById("btn-batch-unanswer"),
    clearButton: document.getElementById("btn-clear"),
    logsRefreshButton: document.getElementById("logs-refresh-button"),
    fetchDictionaryButton: document.getElementById("fetch-dictionary-button"),
    logSearch: document.getElementById("log-search"),
    logAutoscroll: document.getElementById("log-autoscroll"),
    logStream: document.getElementById("log-stream"),
    logsStreamView: document.getElementById("logs-stream-view"),
    loadingOverlay: document.getElementById("loading-overlay"),
    loadingText: document.getElementById("loading-text"),
    loaderSteps: document.getElementById("loader-steps"),
    copyrightYear: document.getElementById("copyright-year"),
    confirmDialog: document.getElementById("confirm-dialog"),
    confirmTitle: document.getElementById("confirm-dialog-title"),
    confirmMessage: document.getElementById("confirm-dialog-message"),
    confirmAcceptButton: document.getElementById("confirm-accept-button"),
    confirmCancelButton: document.getElementById("confirm-cancel-button"),
    render: {
      indicator: document.querySelector(".render-indicator"),
      lamp: document.getElementById("render-lamp"),
      phase: document.getElementById("render-phase"),
      summary: document.getElementById("render-summary"),
      title: document.getElementById("render-title"),
      question: document.getElementById("render-question"),
      updated: document.getElementById("render-updated")
    }
  };
}
