// state.js: オペレーター画面の状態管理と同期ロジックを提供します。
import { OPERATOR_MODE_TELOP } from "../shared/operator-modes.js";

export function createInitialState(autoScroll = true) {
  return {
    questionsByUid: new Map(),
    questionStatusByUid: new Map(),
    allQuestions: [],
    allLogs: [],
    currentSubTab: "all",
    currentGenre: "",
    currentSchedule: "",
    lastNormalSchedule: "",
    availableSchedules: [],
    scheduleDetails: new Map(),
    scheduleMetadata: new Map(),
    activeEventId: "",
    activeScheduleId: "",
    activeEventName: "",
    activeScheduleLabel: "",
    committedScheduleId: "",
    committedScheduleLabel: "",
    committedScheduleKey: "",
    operatorPresenceIntentId: "",
    operatorPresenceIntentLabel: "",
    operatorPresenceIntentKey: "",
    selectionConfirmed: false,
    eventsById: new Map(),
    selectedRowData: null,
    lastDisplayedUid: null,
    autoScrollLogs: autoScroll,
    renderState: null,
    displaySession: null,
    displaySessionActive: false,
    displaySessionLastActive: null,
    displayPresenceEntries: [],
    renderChannelOnline: null,
    displayAssetAvailable: null,
    displayAssetChecked: false,
    displayAssetChecking: false,
    autoLockAttemptKey: "",
    autoLockAttemptAt: 0,
    operatorPresenceEventId: "",
    operatorPresenceByUser: new Map(),
    operatorPresenceSelf: null,
    channelAssignment: null,
    channelLocking: false,
    scheduleConflict: null,
    conflictSelection: "",
    operatorMode: OPERATOR_MODE_TELOP,
    sideTelopChannelKey: "",
    sideTelopLastPushedText: "",
    sideTelopEntries: [],
    sideTelopActiveIndex: 0,
    sideTelopEditingIndex: null,
    sideTelopSelectedIndex: null
  };
}
